version: '3.8'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    container_name: sqlite_db
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  api:
    container_name: jobs_api
    build:
      context: .
      args:
        POETRY_V: "1.0.0"
    env_file:
      - secrets.env
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./src:/project/src
      - ./db/:/project/db/

